openapi: 3.0.0
info:
  title: Mediator controller
  description: This is a sample Mediator controller.  You can find out more about
    our project at [https://github.com/icanlab/mediator-controller)
  contact:
    email: icanlab@pub.seu.edu.cn
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://127.0.0.1/v1
  description: localhost test
paths:
  /mediatorservice/get_device_info:
    get:
      summary: get device information
      operationId: get_device_info
      parameters:
      - name: neid
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: get success
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: operation failed!
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /mediatorservice/get_controller_config:
    get:
      summary: get controller configuration
      operationId: get_controller_config
      parameters:
      - name: neid
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: xpath
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ns_map
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: get success
          content:
            application/xml:
              schema:
                type: string
                x-content-type: application/xml
        "400":
          description: operation failed!
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /mediatorservice/get_device_config:
    get:
      summary: get device configuration
      operationId: get_device_config
      parameters:
      - name: neid
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: xpath
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ns_map
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: get success
          content:
            application/xml:
              schema:
                type: string
                x-content-type: application/xml
        "400":
          description: operation failed!
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas: {}
  securitySchemes: {}
  links: {}
  callbacks: {}

